apiVersion: apps/v1
kind: Deployment
metadata:
  name: csssh-{{ default "staging" .Release.Namespace }}
  namespace: {{ default "staging" .Release.Namespace }}
  labels:
    app: csssh-{{ default "staging" .Release.Namespace }}
  annotations: 
    "builddate": "20220808-01"
spec:
  replicas: {{- if ne .Release.Namespace "production" }}1{{- else }}3{{- end}}
  selector:
    matchLabels:
      app: csssh-{{ default "staging" .Release.Namespace }}
  template:
    metadata:
      labels:
        app: csssh-{{ default "staging" .Release.Namespace }}
    spec:
      containers:
      - name: csssh-{{ default "staging" .Release.Namespace }}
        image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ default "latest" .Values.image.tag }}
        ports:
        - containerPort: 22
        volumeMounts:
        - mountPath: /home
          name: mount0
        - mountPath: /webroot
          name: mount1
        - mountPath: /rprojects
          name: mount2
        - mountPath: /opt/R
          name: mount3
          readOnly: true
        - mountPath: /opt/python
          name: mount4
          readOnly: true
        - mountPath: /opt/anaconda
          name: mount5
          readOnly: true
      volumes:
      - name: mount0
        nfs:
          path: /export/home
          server: aznfs-int.cs.calvin.edu
      - name: mount1
        nfs:
          path: /export/webroot
          server: aznfs-int.cs.calvin.edu
      - name: mount2
        nfs:
          path: /export/rprojects
          server: aznfs-int.cs.calvin.edu
      - name: mount3
        nfs:
          path: /export/r
          server: aznfs-int.cs.calvin.edu
      - name: mount4
        nfs:
          path: /export/python
          server: aznfs-int.cs.calvin.edu
      - name: mount5
        nfs:
          path: /export/anaconda
          server: aznfs-int.cs.calvin.edu
---
apiVersion: v1
kind: Service
metadata:
  name: csssh-{{ default "staging" .Release.Namespace }}
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
  - port: 22
  selector:
    app: csssh-{{ default "staging" .Release.Namespace }}
