apiVersion: apps/v1
kind: Deployment
metadata:
  name: csssh-{{ default "staging" .Release.Namespace }}
  namespace: {{ default "staging" .Release.Namespace }}
  labels:
    app: csssh-{{ default "staging" .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csssh-{{ default "staging" .Release.Namespace }}
  template:
    metadata:
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
      labels:
        app: csssh-{{ default "staging" .Release.Namespace }}
        {{ if ne .Release.Namespace "production" }}name: cs-ssh-{{ .Release.Namespace }}{{- else }}hostname: cs-ssh{{- end }}
    spec:
      {{ if ne .Release.Namespace "production" }}hostname: cs-ssh-{{ .Release.Namespace }}{{- else }}hostname: cs-ssh{{- end }} 
      dnsPolicy: Default
      dnsConfig:
        searches:
          - cs.calvin.edu
      containers:
      - name: csssh-{{ default "staging" .Release.Namespace }}
        image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ default "latest" .Values.image.tag }}
        ports:
        - containerPort: 22
        resources:
          requests:
            memory: "100Mi"
            cpu: "350m" #0.35 CPU
          limits:
            memory: "400Mi"
            cpu: "1000m" #0.1 CPU
        volumeMounts:
        - mountPath: /home
          name: mount0
        - mountPath: /rprojects
          name: mount1
        - mountPath: /opt/R
          name: mount2
          readOnly: true
        - mountPath: /opt/python
          name: mount3
          readOnly: true
        - mountPath: /opt/anaconda
          name: mount4
          readOnly: true
      volumes:
      - name: mount0
        nfs:
          path: /home
          server: katzstunnel.cs.calvin.edu
      - name: mount1
        nfs:
          path: /rprojects
          server: katzstunnel.cs.calvin.edu
      - name: mount2
        nfs:
          path: /r
          server: r-int.cs.calvin.edu
      - name: mount3
        nfs:
          path: /python
          server: r-int.cs.calvin.edu
      - name: mount4
        nfs:
          path: /anaconda
          server: r-int.cs.calvin.edu
---
apiVersion: v1
kind: Service
metadata:
  name: csssh-{{ default "staging" .Release.Namespace }}
  namespace: {{ default "staging" .Release.Namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: cs-ssh{{- if ne .Release.Namespace "production" }}-{{ default "staging" .Release.Namespace }}{{- end }}.{{ .Values.dns.name }}
    service.beta.kubernetes.io/azure-dns-label-name: calvincs-cs-ssh{{- if ne .Release.Namespace "production" }}-{{ default "staging" .Release.Namespace }}{{- end }}
spec:
  type: LoadBalancer
  ports:
  - port: 22
    targetPort: 22
    name: ssh
    protocol: TCP
  selector:
    app: csssh-{{ default "staging" .Release.Namespace }}
---
{{ if eq .Release.Namespace "production" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: csssh-{{ default "staging" .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: csssh-{{ default "staging" .Release.Namespace }}
  minReplicas: 1
  maxReplicas: 2
  #targetCPUUtilizationPercentage: 90
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90
{{- end }}
