apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cssshnfs-aznfs-rprojects-{{ default "staging" .Release.Namespace }}
spec:
  capacity:
    storage: 49Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - soft
    - relatime
    - vers=3
    - namlen=255
    - proto=tcp
    - timeo=600
    - retrans=2
    - sec=sys
    - acl
  nfs:
    path: /export/rprojects
    server: aznfs-int.cs.calvin.edu
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cssshnfs-aznfs-rprojects-{{ default "staging" .Release.Namespace }}
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 49Gi
